language: csharp
matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      dotnet: 2.1.400
      mono: none
    - os: linux
      dist: bionic
      sudo: required
      dotnet: 2.1.400
      mono: none
script:
  - ulimit -n 2048    
  - dotnet restore "src\main\Hangfire.Storage.SQLite" 
  - dotnet build "src\main\Hangfire.Storage.SQLite" -f netstandard2.0
  - dotnet restore "src\test\Hangfire.Storage.SQLite.Test"
  - dotnet build "src\test\Hangfire.Storage.SQLite.Test" -c Release
  - dotnet test "src\test\Hangfire.Storage.SQLite.Test\Hangfire.Storage.SQLite.Test.csproj" --configuration Release --no-build